---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1  # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
      # args: [--strict, -c=/path/to/.yamllint]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013]
        # args: [--disable=MD013,--disable=MD002,--disable=MD032,--disable=MD005,--disable=MD009 ]
        # See https://pre-commit.com for more information
        # See https://pre-commit.com/hooks.html for more hooks
