---
- id: yamllint
  name: yamllint
  description: This hook runs yamllint.
  entry: yamllint
  language: python
  types: [file, yaml]

- id: markdownlint
  name: Markdownlint
  description: Run markdownlint on your Markdown files
  entry: mdl
  language: ruby
  files: \.(md|mdown|markdown)$
