---
name: 'Drift Detection - Terraform Cloud'

on:
  schedule:
    # - cron:  '0 * * * *' # Every hour.
    - cron: '*/5 * * * *'

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    steps:
      - uses: slok/tfe-drift-action@v0.4.0
        id: tfe-drift
        with:
          tfe-token: ${{ secrets.TF_API_TOKEN }}
          tfe-org: shehzad
          limit-max-plans: 3
