---
# This version of drift detection does not work with Terraform cloud
# as it requires remote execution which causes other actions to fail
# https://github.com/marketplace/actions/terraform-cloud-enterprise-drift-detection
# https://github.com/slok/tfe-drift
name: 'Drift Detection - Terraform Cloud'


on:
  workflow_dispatch:
  schedule:
    # - cron:  '0 * * * *' # Every hour.
    # - cron: '*/5 * * * *'
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    steps:
      - uses: slok/tfe-drift-action@v0.4.0
        id: tfe-drift
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          tfe-org: ${{ secrets.TFE_ORGANIZATION }}
          limit-max-plans: 3
