name: 'Drift Detection'

on:
    schedule:
        - cron: '*/30 * * * *'

jobs:
  detect_drift:
    uses: ./.github/workflows/plan.yml
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}      