---
name: Check Port Accessibility

on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Use OIDC Role to checkout the repository with the Github Actions Runner
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

      # # Generates an execution plan for Terraform
      # - name: Terraform Plan Output
      #   run: |
      #     terraform output -json >
      #     terraform output -json plan.tfplan > /tmp/plan.json

      # Apply the Configuration
      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve
          terraform output -json > /tmp/plan.json

      # Extract values from Terraform output
      - name: Extract Terraform Output
        id: extract
        run: |
          ip=$(jq -r '.instance_ip.value' < /tmp/plan.json)
          port=$(jq -r '.instance_port.value' < /tmp/plan.json)
          echo "IP=$ip"
          echo "PORT=$port"
          echo "IP=$ip" >> $GITHUB_ENV
          echo "PORT=$port" >> $GITHUB_ENV

      # Step Check if the port is accessible
      - name: Check Port Accessibility
        run: |
          echo "Checking if $IP:$PORT is accessible..."
          timeout 5 bash -c "cat < /dev/null > /dev/tcp/$IP/$PORT"
          if [ $? -eq 0 ]; then
            echo "Port $PORT on $IP is accessible."
          else
            echo "Port $PORT on $IP is not accessible." >&2
            exit 1
          fi
