---
name: Check Port Accessibility

on:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Use OIDC Role to checkout the repository with the Github Actions Runner
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

      # Apply the Configuration
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve

      - name: Get instance details
        run: |
          # Get the IP of the deployed instance or service via Terraform outputs
          GRAFANA_IP=$(terraform output -raw grafana_ip)

          echo "Grafana IP is: $grafana_ip"
          echo "GRAFANA_IP=$GRAFANA_IP" >> $GITHUB_ENV

      - name: Validate Port Accessibility
        run: |
          # Check if port 3000 is accessible on the instance
          if nc -z -v -w5 $INSTANCE_IP 3000; then
            echo "Port 3000 is accessible on $INSTANCE_IP"
          else
            echo "Port 3000 is NOT accessible on $INSTANCE_IP"
            exit 1
          fi
