---
name: Lint
on:
  push:
    branches: [main, staging]
  pull_request:
  workflow_dispatch:

jobs:
  tflint:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./terraform

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: |
          tflint -f compact > tflint_output.txt
          if [ -s tflint_output.txt ]; then
            echo "TFLINT_FAILED=true" >> $GITHUB_ENV
          else
            echo "TFLINT_FAILED=false" >> $GITHUB_ENV
          fi

      - name: Comment on PR with TFLint Issues
        if: env.TFLINT_FAILED == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const tflintOutput = fs.readFileSync('./terraform/tflint_output.txt', 'utf8');
            const commentBody = `### :warning: TFLint Issues Detected\n\n\`\`\`\n${tflintOutput}\n\`\`\`\nPlease review the above issues reported by TFLint.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
